name = "math_sever"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
aide = { path = "../.." }
mist = ">= 5.0.3 and < 6.0.0"
wisp = ">= 2.1.0 and < 3.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
oas = ">= 7.3.0 and < 8.0.0"
oas_generator_utils = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
